### ISSUE TITLE
Evaluating for all tasks crashes

### ISSUE THREAD

**Issue by akutuzov** [ltgoslo/norbench#9]
Running evaluation on all tasks crashes on the very first one with:

```
Traceback (most recent call last):
  File "norbench/evaluation_scripts/all_tasks.py", line 134, in <module>
    run_models_for_current_task(do_train, tsk, name_sub_info, path_tsk, run_name, model_identifier, epochs, use_seqeval_evaluation_for_ner, use_class_weights_for_sent)
  File "norbench/evaluation_scripts/all_tasks.py", line 82, in run_models_for_current_task
    run_tasks(do_train, current_task, name_sub_info, data_path, model_identifier, run_name, epochs, use_seqeval_evaluation_for_ner, use_class_weights_for_sent)
  File "norbench/evaluation_scripts/all_tasks.py", line 55, in run_tasks
    dev_score =  tasks[current_task]['eval'](data_path, "dev", sub_task_info=name_sub_info, short_model_name=model_identifier, task=current_task)
  File "norbench/evaluation_scripts/pos_finetuning.py", line 37, in test
    test_lang_path = data_path + task
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
```

The command is 
`python3 all_tasks.py --path_to_model MODEL --task all --download_cur_data True --model_name IDENTIFIER`

**Comment by akutuzov** [comment]
In addition, it seems the `model_name` parameter is not used in the "all tasks" mode. Whatever is passed there, the checkpoints are still created with [ugly names produced from the filesystem path to the model](https://github.com/ltgoslo/norbench/blob/main/evaluation_scripts/all_tasks.py#L80). 
Why so?

**Comment by akutuzov** [comment]
Neither of the two bugs is  actually fixed by this PR
